# Generated by Django 5.2.5 on 2025-09-10 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='AI_Composition', max_length=100)),
                ('style', models.CharField(choices=[('Classical', 'Classical'), ('Jazz', 'Jazz'), ('Pop', 'Pop')], max_length=50)),
                ('file', models.FileField(upload_to='compositions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
